### ISSUE TITLE
BioCantor 0.4.5 import error

### ISSUE THREAD

**Issue by diekhans** [InscriptaLabs/BioCantor#1]
In a fresh virtualenv

```
(bctest) % pip install biocantor
(bctest) % python3 -c 'from inscripta.biocantor.parent import Parent'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cluster/home/markd/tmp/bctest/lib/python3.9/site-packages/inscripta/biocantor/parent/__init__.py", line 9, in <module>
    from inscripta.biocantor.parent.parent import Parent, SequenceType  # noqa: F401
  File "/cluster/home/markd/tmp/bctest/lib/python3.9/site-packages/inscripta/biocantor/parent/parent.py", line 13, in <module>
    from inscripta.biocantor.location.strand import Strand
  File "/cluster/home/markd/tmp/bctest/lib/python3.9/site-packages/inscripta/biocantor/location/__init__.py", line 8, in <module>
    from inscripta.biocantor.location.location import Location
  File "/cluster/home/markd/tmp/bctest/lib/python3.9/site-packages/inscripta/biocantor/location/location.py", line 9, in <module>
    from inscripta.biocantor.parent import Parent, SequenceType
ImportError: cannot import name 'Parent' from partially initialized module 'inscripta.biocantor.parent' (most likely due to a circular import) (/cluster/home/markd/tmp/bctest/lib/python3.9/site-packages/inscripta/biocantor/parent/__init__.py)
(bctest) [Exit 1] % 
```

**Comment by pamelarussell** [comment]
Thanks Mark, we haven't found a great way around this circular import, but it works if you import `Location` first:

`python3 -c 'from inscripta.biocantor.location import Location; from inscripta.biocantor.parent import Parent'`

**Comment by ifiddes** [comment]
I have a fix for this in the Inscripta code base; I will try to push the code public ASAP

**Comment by diekhans** [comment]
I was about to show you can fix this with the below idiom.  See also

https://stackoverflow.com/questions/22187279/python-circular-importing

```
--- .emacs.bak/location.py.~1~	2021-08-10 15:55:28.681585476 -0700
+++ location.py	2021-08-11 11:41:07.630260249 -0700
@@ -6,7 +6,7 @@
 from inscripta.biocantor.exc import NoSuchAncestorException, NullParentException
 from inscripta.biocantor.location.distance import DistanceType
 from inscripta.biocantor.location.strand import Strand
-from inscripta.biocantor.parent import Parent, SequenceType
+import inscripta.biocantor.parent as parent
 from inscripta.biocantor.sequence import Sequence
 from inscripta.biocantor.util.object_validation import ObjectValidation
 
@@ -45,7 +45,7 @@
     strand: Strand
 
     # The parent of this Location
-    parent: Parent
+    parent: parent.Parent
 
     # The length (number of positions) of this Location. For subclasses representing discontiguous locations,
     # regions between blocks are not considered
@@ -256,7 +256,7 @@
         """Returns a new Location corresponding to this Location with the given strand"""
 
     @abstractmethod
-    def reset_parent(self, new_parent: Parent) -> "Location":
+    def reset_parent(self, new_parent: parent.Parent) -> "Location":
         """Returns a new Location corresponding to this Location with positions unchanged and pointing
         to a new parent"""
 
@@ -286,7 +286,7 @@
         """Returns a BioPython interval type; since they do not have a shared base class, we need a union"""
         pass
 
-    def first_ancestor_of_type(self, sequence_type: Union[str, SequenceType]) -> Parent:
+    def first_ancestor_of_type(self, sequence_type: Union[str, parent.SequenceType]) -> parent.Parent:
         """Returns the Parent object representing the closest ancestor (parent, parent of parent, etc.)
         of this location which has the given sequence type. Raises NoSuchAncestorException if no ancestor with
         the given type exists."""
@@ -294,14 +294,14 @@
             raise NoSuchAncestorException("Location has no parent")
         return self.parent.first_ancestor_of_type(sequence_type, include_self=True)
 
-    def has_ancestor_of_type(self, sequence_type: Union[str, SequenceType]) -> bool:
+    def has_ancestor_of_type(self, sequence_type: Union[str, parent.SequenceType]) -> bool:
         """Returns True if some ancestor (parent, parent of parent, etc.) of of this location has the given sequence
         type, or False otherwise."""
         if not self.parent:
             return False
         return self.parent.has_ancestor_of_type(sequence_type, include_self=True)
 
-    def lift_over_to_first_ancestor_of_type(self, sequence_type: Union[str, SequenceType]) -> "Location":
+    def lift_over_to_first_ancestor_of_type(self, sequence_type: Union[str, parent.SequenceType]) -> "Location":
         """Returns a new Location representing the liftover of this Location to its closest ancestor sequence (parent,
         parent of parent, etc.) which has the given sequence type. If the immediate parent has the given type,
         returns this Location. Raises NoSuchAncestorException if no ancestor with the given type exists."""

```
